on:
  push:
    tags:
      - 'twp/v*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/ynn1e/hello
          tags: type=match,pattern=twp/v(\d.\d.\d)
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ynn1e
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}