# https://songmu.jp/riji/entry/2022-01-06-github-actions-ghcr.html
on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ghcr.io/ynn1e/hello
          tags: |
            type=semver,pattern={{version}}
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ynn1e
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}